"""Generate src/core/NeedIds.h and the [Needs] INI block from needs.csv.

    python -I tools/needs/make_need_ids.py            # write src/core/NeedIds.h
    python -I tools/needs/make_need_ids.py --ini      # print the [Needs] block
    python -I tools/needs/make_need_ids.py --check    # exit 1 if either is stale

needs.csv (docs/architecture/9-data/) is the source: id, group, priority,
curve_kind, curve_p1, curve_p2, r3_input. A need whose r3_input starts with
"0 (deferred" has no sensor yet (it always reads input 0). The host test
tests/core/NeedIdsTests.cpp checks NeedIds.h against the csv on every build;
--check also compares the [Needs] block in configs/Huginn.ini.
"""
import csv
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CSV = os.path.join(ROOT, "docs", "architecture", "9-data", "needs.csv")
HEADER = os.path.join(ROOT, "src", "core", "NeedIds.h")
INI = os.path.join(ROOT, "configs", "Huginn.ini")
KINDS = {"logistic": "Logistic", "linear": "Linear", "quadratic": "Quadratic",
         "saturating": "Saturating", "gaussian": "Gaussian", "step": "Step", "decay": "Decay"}


def read_rows():
    with open(CSV, encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        if r["curve_kind"] not in KINDS:
            raise SystemExit(f"{r['id']}: unknown curve_kind {r['curve_kind']!r}")
        float(r["curve_p1"])
        float(r["curve_p2"])
    return rows


def cfloat(text):
    v = float(text)
    s = repr(v)
    if "e" not in s and "." not in s:
        s += ".0"
    return s + "f"


def deferred(r):
    return r["r3_input"].startswith("0 (deferred")


def make_header(rows):
    groups = []
    for r in rows:
        if r["group"] not in groups:
            groups.append(r["group"])
    n_deferred = sum(1 for r in rows if deferred(r))
    out = []
    w = out.append
    w("#pragma once")
    w("")
    w("// =============================================================================")
    w(f"// NEED IDS -- the {len(rows)} needs of docs/architecture/9-data/needs.csv, in order")
    w("// =============================================================================")
    w("// GENERATED by tools/needs/make_need_ids.py from needs.csv (id, group,")
    w("// priority, curve_kind, curve_p1, curve_p2, r3_input); do not edit by hand.")
    w("// tests/core/NeedIdsTests.cpp fails if the two drift apart. Each enum name is")
    w("// the csv id, so a need reads the same in code, logs, `hg needs` and docs.")
    w("//")
    w(f"// `curve` is the default response curve (the [Needs] INI section overrides")
    w(f"// it per need); `deferred` marks the {n_deferred} needs whose sensor is not built yet")
    w("// (their r3_input reads \"0 (deferred: ...)\"): they always read input 0.")
    w("//")
    w("// Pure: standard library only (src/core/README.md).")
    w("// =============================================================================")
    w("")
    w('#include "ResponseCurve.h"')
    w("")
    w("#include <array>")
    w("#include <cstddef>")
    w("#include <cstdint>")
    w("#include <optional>")
    w("#include <string_view>")
    w("")
    w("namespace Huginn::Core::Needs")
    w("{")
    w("    enum class NeedId : std::uint8_t")
    w("    {")
    for r in rows:
        w(f"        {r['id']},")
    w("        _Count")
    w("    };")
    w("")
    w(f"    inline constexpr std::size_t kNeedCount = {len(rows)};")
    w("    static_assert(static_cast<std::size_t>(NeedId::_Count) == kNeedCount);")
    w("")
    w("    struct NeedInfo")
    w("    {")
    w("        std::string_view id;")
    w("        std::string_view group;")
    w("        Curve curve;           // default (csv curve_kind, curve_p1, curve_p2)")
    w("        std::uint8_t priority;  // 1, 2 or 3 (csv P1..P3)")
    w("        bool deferred;         // no sensor yet: input is always 0")
    w("    };")
    w("")
    w("    inline constexpr std::array<NeedInfo, kNeedCount> kNeeds{ {")
    for r in rows:
        kind = KINDS[r["curve_kind"]]
        prio = int(r["priority"].lstrip("P"))
        w(f'        {{ "{r["id"]}", "{r["group"]}", {{ CurveKind::{kind}, {cfloat(r["curve_p1"])}, '
          f'{cfloat(r["curve_p2"])} }}, {prio}, {"true" if deferred(r) else "false"} }},')
    w("    } };")
    w("")
    w("    [[nodiscard]] constexpr std::size_t Index(NeedId id) noexcept { return static_cast<std::size_t>(id); }")
    w("    [[nodiscard]] constexpr const NeedInfo& Info(NeedId id) noexcept { return kNeeds[Index(id)]; }")
    w("    [[nodiscard]] constexpr std::string_view Name(NeedId id) noexcept { return Info(id).id; }")
    w("")
    w("    [[nodiscard]] constexpr std::optional<NeedId> FromName(std::string_view name) noexcept")
    w("    {")
    w("        for (std::size_t i = 0; i < kNeedCount; ++i) {")
    w("            if (kNeeds[i].id == name) return static_cast<NeedId>(i);")
    w("        }")
    w("        return std::nullopt;")
    w("    }")
    w("}")
    w("")
    return "\n".join(out)


def make_ini(rows):
    out = []
    w = out.append
    w("[Needs]")
    w("; R3 (0.23.14): the need vector -- one value per need in")
    w(";   docs/architecture/9-data/needs.csv, computed each tick and LOGGED ONLY: no")
    w(";   score reads it yet. `hg needs` prints it. One key per need, the need's id:")
    w(";     <need> = <kind> <p1> <p2>")
    w(";   kinds: logistic (centre, slope; a negative slope falls), linear and")
    w(";   quadratic (x0, x1: 0 at x0, 1 at x1), saturating (s > 0), gaussian")
    w(";   (centre, width > 0), step (edge), decay (tau > 0). The values below are")
    w(";   the csv's defaults (curve_kind, curve_p1, curve_p2); a key left out or")
    w(";   unreadable keeps its default. Hot-reloadable (hg reload / dMenu).")
    w(";   darkness's centre mirrors 1 - [ContextWeights] fDarkLightLevel.")
    group = None
    for r in rows:
        if r["group"] != group:
            group = r["group"]
            w(f"; -- {group}")
        p1 = r["curve_p1"]
        p2 = r["curve_p2"]
        if deferred(r):
            w(f"; {r['id']}: deferred, no sensor yet (reads input 0)")
        w(f"{r['id']} = {r['curve_kind']} {p1} {p2}")
    return "\n".join(out) + "\n"


def ini_block_in_file():
    with open(INI, encoding="utf-8-sig", newline="") as f:
        text = f.read().replace("\r\n", "\n")
    start = text.find("\n[Needs]\n")
    if start < 0:
        return None
    start += 1
    end = text.find("\n[", start + 1)
    return text[start:] if end < 0 else text[start:end + 1]


def main(argv):
    unknown = [a for a in argv if a not in ("--ini", "--check", "-h", "--help")]
    if unknown or len(argv) > 1:
        print(f"unknown or extra argument(s): {' '.join(argv)}\n\n{__doc__.strip()}", file=sys.stderr)
        return 2
    if argv and argv[0] in ("-h", "--help"):
        print(__doc__.strip())
        return 0
    rows = read_rows()
    header = make_header(rows)
    ini = make_ini(rows)
    if "--ini" in argv:
        sys.stdout.write(ini)
        return 0
    if "--check" in argv:
        ok = True
        with open(HEADER, encoding="utf-8", newline="") as f:
            if f.read().replace("\r\n", "\n") != header:
                print("STALE: src/core/NeedIds.h (run tools/needs/make_need_ids.py)")
                ok = False
        block = ini_block_in_file()
        if block is None or block.rstrip("\n") + "\n" != ini:
            print("STALE: configs/Huginn.ini [Needs] block (paste --ini output)")
            ok = False
        print("OK" if ok else "FAILED")
        return 0 if ok else 1
    with open(HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    print(f"wrote {HEADER} ({len(rows)} needs)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
