#pragma once

// =============================================================================
// EFFECT COLUMNS -- the 239 columns of cap(i), in the order of effects.csv
// =============================================================================
// GENERATED from docs/architecture/9-data/effects.csv (id, level, family);
// tests/core/EffectColumnsTests.cpp fails if the two drift apart. Each enum
// name is the CSV id, so a column reads the same in code, dumps and docs.
//
// Levels: 25 families (max over their specifics), 133 specifics, 19
// modifiers, 25 item features, 23 weapon stats, 14 armour stats. Two
// specifics have no family column: drain_skill and soul_trap.
//
// Pure: standard library only (src/core/README.md).
// =============================================================================

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>

namespace Huginn::Core::Effect
{
    enum class Col : std::uint16_t
    {
        restore,
        fortify_vital,
        regen,
        damage,
        absorb,
        drain_vital,
        weaken_regen,
        resist,
        weakness,
        defense,
        fortify_skill,
        fortify_combat,
        weaken_combat,
        control,
        influence,
        summon,
        cure,
        vision,
        stealth,
        movement,
        utility,
        shout,
        survival,
        transform,
        meta,
        restore_health,
        restore_magicka,
        restore_stamina,
        restore_health_other,
        fortify_vital_health,
        fortify_vital_magicka,
        fortify_vital_stamina,
        regen_health,
        regen_magicka,
        regen_stamina,
        damage_health_fire,
        damage_health_frost,
        damage_health_shock,
        damage_health_poison,
        damage_health_magic,
        damage_health_sun,
        damage_health_physical,
        damage_health_disease,
        damage_magicka,
        damage_stamina,
        absorb_health,
        absorb_magicka,
        absorb_stamina,
        drain_vital_health,
        drain_vital_magicka,
        drain_vital_stamina,
        weaken_regen_health,
        weaken_regen_magicka,
        weaken_regen_stamina,
        resist_fire,
        resist_frost,
        resist_shock,
        resist_poison,
        resist_magic,
        resist_disease,
        weakness_fire,
        weakness_frost,
        weakness_shock,
        weakness_poison,
        weakness_magic,
        weakness_armor,
        defense_armor,
        defense_ward,
        defense_spell_absorb,
        defense_reflect,
        defense_ethereal,
        defense_resist_ranged,
        defense_resist_power_attack,
        defense_resist_stagger,
        fortify_skill_one_handed,
        fortify_skill_two_handed,
        fortify_skill_archery,
        fortify_skill_block,
        fortify_skill_heavy_armor,
        fortify_skill_light_armor,
        fortify_skill_smithing,
        fortify_skill_alchemy,
        fortify_skill_enchanting,
        fortify_skill_sneak,
        fortify_skill_lockpicking,
        fortify_skill_pickpocket,
        fortify_skill_speech,
        fortify_skill_alteration,
        fortify_skill_conjuration,
        fortify_skill_destruction,
        fortify_skill_illusion,
        fortify_skill_restoration,
        drain_skill,
        fortify_combat_attack_damage,
        fortify_combat_weapon_speed,
        fortify_combat_unarmed,
        fortify_combat_power_attack,
        fortify_combat_sneak_attack,
        fortify_combat_bash,
        fortify_combat_armor_penetration,
        fortify_combat_crit,
        weaken_combat_attack_damage,
        weaken_combat_weapon_speed,
        control_paralysis,
        control_stagger,
        control_slow,
        control_disarm,
        control_silence,
        control_sleep,
        control_blind,
        control_grab,
        influence_fear,
        influence_calm,
        influence_frenzy,
        influence_rally,
        influence_command,
        influence_turn_undead,
        influence_banish,
        summon_creature_fire,
        summon_creature_frost,
        summon_creature_shock,
        summon_creature,
        summon_reanimate,
        summon_bound_weapon,
        cure_disease,
        cure_poison,
        cure_paralysis,
        cure_dispel,
        cure_injury,
        vision_light,
        vision_night_eye,
        vision_detect_life,
        vision_clairvoyance,
        stealth_invisibility,
        stealth_muffle,
        stealth_disguise,
        movement_speed,
        movement_jump_fall,
        movement_water_walking,
        utility_carry_weight,
        utility_water_breathing,
        utility_telekinesis,
        utility_unlock,
        utility_slow_time,
        utility_teleport,
        utility_transmute,
        utility_size,
        shout_recovery,
        soul_trap,
        survival_hunger,
        survival_thirst,
        survival_warmth,
        survival_fatigue,
        survival_intoxication,
        transform_werewolf,
        transform_vampire_lord,
        meta_xp_gain,
        meta_potion_duration,
        delivery_self,
        delivery_touch,
        delivery_aimed,
        delivery_target_location,
        area,
        hostile,
        aura,
        ground_area,
        timing_instant,
        timing_over_time,
        timing_constant,
        duration,
        long_lasting,
        full_restore,
        concentration,
        magicka_cost,
        cure_instant,
        consumable,
        gold_value,
        kind_spell,
        kind_scroll,
        kind_staff,
        kind_potion,
        kind_poison,
        kind_food,
        kind_weapon,
        kind_ammo,
        kind_armour,
        kind_soulgem,
        kind_light,
        school_alteration,
        school_conjuration,
        school_destruction,
        school_illusion,
        school_restoration,
        overshoot_health,
        overshoot_magicka,
        overshoot_stamina,
        school_fortified,
        ammo_matches_launcher,
        soulgem_charge,
        soulgem_capacity,
        light_radius,
        stack_count,
        weapon_type_sword,
        weapon_type_dagger,
        weapon_type_war_axe,
        weapon_type_mace,
        weapon_type_greatsword,
        weapon_type_battleaxe,
        weapon_type_warhammer,
        weapon_type_bow,
        weapon_type_crossbow,
        weapon_melee,
        weapon_ranged,
        weapon_two_handed,
        weapon_damage,
        weapon_speed,
        weapon_reach,
        weapon_crit,
        weapon_enchanted,
        weapon_charge,
        weapon_silver,
        weapon_pickaxe,
        ammo_arrow,
        ammo_bolt,
        ammo_damage,
        armour_slot_head,
        armour_slot_body,
        armour_slot_hands,
        armour_slot_feet,
        armour_slot_shield,
        armour_slot_amulet,
        armour_slot_ring,
        armour_weight_heavy,
        armour_weight_light,
        armour_weight_clothing,
        armour_rating,
        armour_enchanted,
        armour_warm,
        armour_cold,
        _Count
    };

    inline constexpr std::size_t kColumnCount = static_cast<std::size_t>(Col::_Count);
    static_assert(kColumnCount == 239, "effects.csv has 239 columns");

    enum class Level : std::uint8_t { Family, Specific, Modifier, ItemFeature, WeaponStat, ArmourStat };

    struct ColumnInfo
    {
        std::string_view id;
        Level level;
        Col family;  // the family column of a specific; Col::_Count if none
    };

    inline constexpr std::array<ColumnInfo, kColumnCount> kColumns{ {
        { "restore", Level::Family, Col::_Count },
        { "fortify_vital", Level::Family, Col::_Count },
        { "regen", Level::Family, Col::_Count },
        { "damage", Level::Family, Col::_Count },
        { "absorb", Level::Family, Col::_Count },
        { "drain_vital", Level::Family, Col::_Count },
        { "weaken_regen", Level::Family, Col::_Count },
        { "resist", Level::Family, Col::_Count },
        { "weakness", Level::Family, Col::_Count },
        { "defense", Level::Family, Col::_Count },
        { "fortify_skill", Level::Family, Col::_Count },
        { "fortify_combat", Level::Family, Col::_Count },
        { "weaken_combat", Level::Family, Col::_Count },
        { "control", Level::Family, Col::_Count },
        { "influence", Level::Family, Col::_Count },
        { "summon", Level::Family, Col::_Count },
        { "cure", Level::Family, Col::_Count },
        { "vision", Level::Family, Col::_Count },
        { "stealth", Level::Family, Col::_Count },
        { "movement", Level::Family, Col::_Count },
        { "utility", Level::Family, Col::_Count },
        { "shout", Level::Family, Col::_Count },
        { "survival", Level::Family, Col::_Count },
        { "transform", Level::Family, Col::_Count },
        { "meta", Level::Family, Col::_Count },
        { "restore_health", Level::Specific, Col::restore },
        { "restore_magicka", Level::Specific, Col::restore },
        { "restore_stamina", Level::Specific, Col::restore },
        { "restore_health_other", Level::Specific, Col::restore },
        { "fortify_vital_health", Level::Specific, Col::fortify_vital },
        { "fortify_vital_magicka", Level::Specific, Col::fortify_vital },
        { "fortify_vital_stamina", Level::Specific, Col::fortify_vital },
        { "regen_health", Level::Specific, Col::regen },
        { "regen_magicka", Level::Specific, Col::regen },
        { "regen_stamina", Level::Specific, Col::regen },
        { "damage_health_fire", Level::Specific, Col::damage },
        { "damage_health_frost", Level::Specific, Col::damage },
        { "damage_health_shock", Level::Specific, Col::damage },
        { "damage_health_poison", Level::Specific, Col::damage },
        { "damage_health_magic", Level::Specific, Col::damage },
        { "damage_health_sun", Level::Specific, Col::damage },
        { "damage_health_physical", Level::Specific, Col::damage },
        { "damage_health_disease", Level::Specific, Col::damage },
        { "damage_magicka", Level::Specific, Col::damage },
        { "damage_stamina", Level::Specific, Col::damage },
        { "absorb_health", Level::Specific, Col::absorb },
        { "absorb_magicka", Level::Specific, Col::absorb },
        { "absorb_stamina", Level::Specific, Col::absorb },
        { "drain_vital_health", Level::Specific, Col::drain_vital },
        { "drain_vital_magicka", Level::Specific, Col::drain_vital },
        { "drain_vital_stamina", Level::Specific, Col::drain_vital },
        { "weaken_regen_health", Level::Specific, Col::weaken_regen },
        { "weaken_regen_magicka", Level::Specific, Col::weaken_regen },
        { "weaken_regen_stamina", Level::Specific, Col::weaken_regen },
        { "resist_fire", Level::Specific, Col::resist },
        { "resist_frost", Level::Specific, Col::resist },
        { "resist_shock", Level::Specific, Col::resist },
        { "resist_poison", Level::Specific, Col::resist },
        { "resist_magic", Level::Specific, Col::resist },
        { "resist_disease", Level::Specific, Col::resist },
        { "weakness_fire", Level::Specific, Col::weakness },
        { "weakness_frost", Level::Specific, Col::weakness },
        { "weakness_shock", Level::Specific, Col::weakness },
        { "weakness_poison", Level::Specific, Col::weakness },
        { "weakness_magic", Level::Specific, Col::weakness },
        { "weakness_armor", Level::Specific, Col::weakness },
        { "defense_armor", Level::Specific, Col::defense },
        { "defense_ward", Level::Specific, Col::defense },
        { "defense_spell_absorb", Level::Specific, Col::defense },
        { "defense_reflect", Level::Specific, Col::defense },
        { "defense_ethereal", Level::Specific, Col::defense },
        { "defense_resist_ranged", Level::Specific, Col::defense },
        { "defense_resist_power_attack", Level::Specific, Col::defense },
        { "defense_resist_stagger", Level::Specific, Col::defense },
        { "fortify_skill_one_handed", Level::Specific, Col::fortify_skill },
        { "fortify_skill_two_handed", Level::Specific, Col::fortify_skill },
        { "fortify_skill_archery", Level::Specific, Col::fortify_skill },
        { "fortify_skill_block", Level::Specific, Col::fortify_skill },
        { "fortify_skill_heavy_armor", Level::Specific, Col::fortify_skill },
        { "fortify_skill_light_armor", Level::Specific, Col::fortify_skill },
        { "fortify_skill_smithing", Level::Specific, Col::fortify_skill },
        { "fortify_skill_alchemy", Level::Specific, Col::fortify_skill },
        { "fortify_skill_enchanting", Level::Specific, Col::fortify_skill },
        { "fortify_skill_sneak", Level::Specific, Col::fortify_skill },
        { "fortify_skill_lockpicking", Level::Specific, Col::fortify_skill },
        { "fortify_skill_pickpocket", Level::Specific, Col::fortify_skill },
        { "fortify_skill_speech", Level::Specific, Col::fortify_skill },
        { "fortify_skill_alteration", Level::Specific, Col::fortify_skill },
        { "fortify_skill_conjuration", Level::Specific, Col::fortify_skill },
        { "fortify_skill_destruction", Level::Specific, Col::fortify_skill },
        { "fortify_skill_illusion", Level::Specific, Col::fortify_skill },
        { "fortify_skill_restoration", Level::Specific, Col::fortify_skill },
        { "drain_skill", Level::Specific, Col::_Count },
        { "fortify_combat_attack_damage", Level::Specific, Col::fortify_combat },
        { "fortify_combat_weapon_speed", Level::Specific, Col::fortify_combat },
        { "fortify_combat_unarmed", Level::Specific, Col::fortify_combat },
        { "fortify_combat_power_attack", Level::Specific, Col::fortify_combat },
        { "fortify_combat_sneak_attack", Level::Specific, Col::fortify_combat },
        { "fortify_combat_bash", Level::Specific, Col::fortify_combat },
        { "fortify_combat_armor_penetration", Level::Specific, Col::fortify_combat },
        { "fortify_combat_crit", Level::Specific, Col::fortify_combat },
        { "weaken_combat_attack_damage", Level::Specific, Col::weaken_combat },
        { "weaken_combat_weapon_speed", Level::Specific, Col::weaken_combat },
        { "control_paralysis", Level::Specific, Col::control },
        { "control_stagger", Level::Specific, Col::control },
        { "control_slow", Level::Specific, Col::control },
        { "control_disarm", Level::Specific, Col::control },
        { "control_silence", Level::Specific, Col::control },
        { "control_sleep", Level::Specific, Col::control },
        { "control_blind", Level::Specific, Col::control },
        { "control_grab", Level::Specific, Col::control },
        { "influence_fear", Level::Specific, Col::influence },
        { "influence_calm", Level::Specific, Col::influence },
        { "influence_frenzy", Level::Specific, Col::influence },
        { "influence_rally", Level::Specific, Col::influence },
        { "influence_command", Level::Specific, Col::influence },
        { "influence_turn_undead", Level::Specific, Col::influence },
        { "influence_banish", Level::Specific, Col::influence },
        { "summon_creature_fire", Level::Specific, Col::summon },
        { "summon_creature_frost", Level::Specific, Col::summon },
        { "summon_creature_shock", Level::Specific, Col::summon },
        { "summon_creature", Level::Specific, Col::summon },
        { "summon_reanimate", Level::Specific, Col::summon },
        { "summon_bound_weapon", Level::Specific, Col::summon },
        { "cure_disease", Level::Specific, Col::cure },
        { "cure_poison", Level::Specific, Col::cure },
        { "cure_paralysis", Level::Specific, Col::cure },
        { "cure_dispel", Level::Specific, Col::cure },
        { "cure_injury", Level::Specific, Col::cure },
        { "vision_light", Level::Specific, Col::vision },
        { "vision_night_eye", Level::Specific, Col::vision },
        { "vision_detect_life", Level::Specific, Col::vision },
        { "vision_clairvoyance", Level::Specific, Col::vision },
        { "stealth_invisibility", Level::Specific, Col::stealth },
        { "stealth_muffle", Level::Specific, Col::stealth },
        { "stealth_disguise", Level::Specific, Col::stealth },
        { "movement_speed", Level::Specific, Col::movement },
        { "movement_jump_fall", Level::Specific, Col::movement },
        { "movement_water_walking", Level::Specific, Col::movement },
        { "utility_carry_weight", Level::Specific, Col::utility },
        { "utility_water_breathing", Level::Specific, Col::utility },
        { "utility_telekinesis", Level::Specific, Col::utility },
        { "utility_unlock", Level::Specific, Col::utility },
        { "utility_slow_time", Level::Specific, Col::utility },
        { "utility_teleport", Level::Specific, Col::utility },
        { "utility_transmute", Level::Specific, Col::utility },
        { "utility_size", Level::Specific, Col::utility },
        { "shout_recovery", Level::Specific, Col::shout },
        { "soul_trap", Level::Specific, Col::_Count },
        { "survival_hunger", Level::Specific, Col::survival },
        { "survival_thirst", Level::Specific, Col::survival },
        { "survival_warmth", Level::Specific, Col::survival },
        { "survival_fatigue", Level::Specific, Col::survival },
        { "survival_intoxication", Level::Specific, Col::survival },
        { "transform_werewolf", Level::Specific, Col::transform },
        { "transform_vampire_lord", Level::Specific, Col::transform },
        { "meta_xp_gain", Level::Specific, Col::meta },
        { "meta_potion_duration", Level::Specific, Col::meta },
        { "delivery_self", Level::Modifier, Col::_Count },
        { "delivery_touch", Level::Modifier, Col::_Count },
        { "delivery_aimed", Level::Modifier, Col::_Count },
        { "delivery_target_location", Level::Modifier, Col::_Count },
        { "area", Level::Modifier, Col::_Count },
        { "hostile", Level::Modifier, Col::_Count },
        { "aura", Level::Modifier, Col::_Count },
        { "ground_area", Level::Modifier, Col::_Count },
        { "timing_instant", Level::Modifier, Col::_Count },
        { "timing_over_time", Level::Modifier, Col::_Count },
        { "timing_constant", Level::Modifier, Col::_Count },
        { "duration", Level::Modifier, Col::_Count },
        { "long_lasting", Level::Modifier, Col::_Count },
        { "full_restore", Level::Modifier, Col::_Count },
        { "concentration", Level::Modifier, Col::_Count },
        { "magicka_cost", Level::Modifier, Col::_Count },
        { "cure_instant", Level::Modifier, Col::_Count },
        { "consumable", Level::Modifier, Col::_Count },
        { "gold_value", Level::Modifier, Col::_Count },
        { "kind_spell", Level::ItemFeature, Col::_Count },
        { "kind_scroll", Level::ItemFeature, Col::_Count },
        { "kind_staff", Level::ItemFeature, Col::_Count },
        { "kind_potion", Level::ItemFeature, Col::_Count },
        { "kind_poison", Level::ItemFeature, Col::_Count },
        { "kind_food", Level::ItemFeature, Col::_Count },
        { "kind_weapon", Level::ItemFeature, Col::_Count },
        { "kind_ammo", Level::ItemFeature, Col::_Count },
        { "kind_armour", Level::ItemFeature, Col::_Count },
        { "kind_soulgem", Level::ItemFeature, Col::_Count },
        { "kind_light", Level::ItemFeature, Col::_Count },
        { "school_alteration", Level::ItemFeature, Col::_Count },
        { "school_conjuration", Level::ItemFeature, Col::_Count },
        { "school_destruction", Level::ItemFeature, Col::_Count },
        { "school_illusion", Level::ItemFeature, Col::_Count },
        { "school_restoration", Level::ItemFeature, Col::_Count },
        { "overshoot_health", Level::ItemFeature, Col::_Count },
        { "overshoot_magicka", Level::ItemFeature, Col::_Count },
        { "overshoot_stamina", Level::ItemFeature, Col::_Count },
        { "school_fortified", Level::ItemFeature, Col::_Count },
        { "ammo_matches_launcher", Level::ItemFeature, Col::_Count },
        { "soulgem_charge", Level::ItemFeature, Col::_Count },
        { "soulgem_capacity", Level::ItemFeature, Col::_Count },
        { "light_radius", Level::ItemFeature, Col::_Count },
        { "stack_count", Level::ItemFeature, Col::_Count },
        { "weapon_type_sword", Level::WeaponStat, Col::_Count },
        { "weapon_type_dagger", Level::WeaponStat, Col::_Count },
        { "weapon_type_war_axe", Level::WeaponStat, Col::_Count },
        { "weapon_type_mace", Level::WeaponStat, Col::_Count },
        { "weapon_type_greatsword", Level::WeaponStat, Col::_Count },
        { "weapon_type_battleaxe", Level::WeaponStat, Col::_Count },
        { "weapon_type_warhammer", Level::WeaponStat, Col::_Count },
        { "weapon_type_bow", Level::WeaponStat, Col::_Count },
        { "weapon_type_crossbow", Level::WeaponStat, Col::_Count },
        { "weapon_melee", Level::WeaponStat, Col::_Count },
        { "weapon_ranged", Level::WeaponStat, Col::_Count },
        { "weapon_two_handed", Level::WeaponStat, Col::_Count },
        { "weapon_damage", Level::WeaponStat, Col::_Count },
        { "weapon_speed", Level::WeaponStat, Col::_Count },
        { "weapon_reach", Level::WeaponStat, Col::_Count },
        { "weapon_crit", Level::WeaponStat, Col::_Count },
        { "weapon_enchanted", Level::WeaponStat, Col::_Count },
        { "weapon_charge", Level::WeaponStat, Col::_Count },
        { "weapon_silver", Level::WeaponStat, Col::_Count },
        { "weapon_pickaxe", Level::WeaponStat, Col::_Count },
        { "ammo_arrow", Level::WeaponStat, Col::_Count },
        { "ammo_bolt", Level::WeaponStat, Col::_Count },
        { "ammo_damage", Level::WeaponStat, Col::_Count },
        { "armour_slot_head", Level::ArmourStat, Col::_Count },
        { "armour_slot_body", Level::ArmourStat, Col::_Count },
        { "armour_slot_hands", Level::ArmourStat, Col::_Count },
        { "armour_slot_feet", Level::ArmourStat, Col::_Count },
        { "armour_slot_shield", Level::ArmourStat, Col::_Count },
        { "armour_slot_amulet", Level::ArmourStat, Col::_Count },
        { "armour_slot_ring", Level::ArmourStat, Col::_Count },
        { "armour_weight_heavy", Level::ArmourStat, Col::_Count },
        { "armour_weight_light", Level::ArmourStat, Col::_Count },
        { "armour_weight_clothing", Level::ArmourStat, Col::_Count },
        { "armour_rating", Level::ArmourStat, Col::_Count },
        { "armour_enchanted", Level::ArmourStat, Col::_Count },
        { "armour_warm", Level::ArmourStat, Col::_Count },
        { "armour_cold", Level::ArmourStat, Col::_Count },
    } };

    [[nodiscard]] constexpr std::size_t Index(Col c) noexcept { return static_cast<std::size_t>(c); }
    [[nodiscard]] constexpr const ColumnInfo& Info(Col c) noexcept { return kColumns[Index(c)]; }
    [[nodiscard]] constexpr std::string_view Name(Col c) noexcept
    {
        return c < Col::_Count ? kColumns[Index(c)].id : std::string_view{};
    }
    [[nodiscard]] constexpr Level LevelOf(Col c) noexcept { return kColumns[Index(c)].level; }
    [[nodiscard]] constexpr Col FamilyOf(Col c) noexcept { return kColumns[Index(c)].family; }

    /// The column whose id is `name`, if any (linear: for tests, tools and the console).
    [[nodiscard]] constexpr std::optional<Col> FromName(std::string_view name) noexcept
    {
        for (std::size_t i = 0; i < kColumnCount; ++i) {
            if (kColumns[i].id == name) return static_cast<Col>(i);
        }
        return std::nullopt;
    }

    /// An effect column (family or specific): what an item's effects do, as
    /// opposed to its modifiers, kind and stats.
    [[nodiscard]] constexpr bool IsEffect(Col c) noexcept
    {
        const auto l = LevelOf(c);
        return l == Level::Family || l == Level::Specific;
    }
}
