#pragma once

// =============================================================================
// NEED IDS -- the 92 needs of docs/architecture/9-data/needs.csv, in order
// =============================================================================
// GENERATED by tools/needs/make_need_ids.py from needs.csv (id, group,
// priority, curve_kind, curve_p1, curve_p2, r3_input); do not edit by hand.
// tests/core/NeedIdsTests.cpp fails if the two drift apart. Each enum name is
// the csv id, so a need reads the same in code, logs, `hg needs` and docs.
//
// `curve` is the default response curve (the [Needs] INI section overrides
// it per need); `deferred` marks the 5 needs whose sensor is not built yet
// (their r3_input reads "0 (deferred: ...)"): they always read input 0.
//
// Pure: standard library only (src/core/README.md).
// =============================================================================

#include "ResponseCurve.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>

namespace Huginn::Core::Needs
{
    enum class NeedId : std::uint8_t
    {
        health_deficit,
        magicka_deficit,
        stamina_deficit,
        health_falling,
        magicka_burn,
        stamina_burn,
        restore_pending_health,
        restore_pending_magicka,
        restore_pending_stamina,
        fire_damage_rate,
        frost_damage_rate,
        shock_damage_rate,
        magic_damage_rate,
        physical_damage_rate,
        enemy_casting_fire,
        enemy_casting_frost,
        enemy_casting_shock,
        poisoned,
        diseased,
        drain_health,
        drain_magicka,
        drain_stamina,
        regen_suppressed,
        healing_blocked,
        encumbrance,
        vampire_sun_exposure,
        hunger,
        thirst,
        cold,
        fatigue,
        warmth_deficit,
        in_combat,
        combat_onset,
        enemy_count,
        enemy_close,
        enemy_mid,
        enemy_far,
        surrounded,
        enemy_casting,
        target_caster,
        target_archer,
        target_health_low,
        boss_fight,
        target_magicka_low,
        target_stamina_low,
        target_humanoid,
        target_undead,
        target_daedra,
        target_dragon,
        target_construct,
        target_animal,
        target_arthropod,
        target_troll,
        target_giant,
        target_werebeast,
        target_monster,
        target_spectral,
        target_element_fire,
        target_element_frost,
        target_element_shock,
        target_summoned,
        ally_injured,
        follower_present,
        darkness,
        underwater,
        swimming,
        falling,
        drop_ahead,
        lock_in_crosshair,
        workstation_smithing,
        workstation_enchanting,
        workstation_alchemy,
        ore_vein_in_crosshair,
        merchant_in_crosshair,
        weapon_charge_deficit,
        ammo_low,
        hands_empty,
        loadout_one_handed,
        loadout_two_handed,
        loadout_archery,
        loadout_staff,
        loadout_shield,
        loadout_destruction,
        loadout_conjuration,
        loadout_restoration,
        loadout_alteration,
        loadout_illusion,
        sneaking,
        sneak_detected,
        mounted,
        downtime,
        combat_ended_recent,
        _Count
    };

    inline constexpr std::size_t kNeedCount = 92;
    static_assert(static_cast<std::size_t>(NeedId::_Count) == kNeedCount);

    struct NeedInfo
    {
        std::string_view id;
        std::string_view group;
        Curve curve;           // default (csv curve_kind, curve_p1, curve_p2)
        std::uint8_t priority;  // 1, 2 or 3 (csv P1..P3)
        bool deferred;         // no sensor yet: input is always 0
    };

    inline constexpr std::array<NeedInfo, kNeedCount> kNeeds{ {
        { "health_deficit", "Vitals", { CurveKind::Logistic, 0.5f, 10.0f }, 1, false },
        { "magicka_deficit", "Vitals", { CurveKind::Logistic, 0.5f, 10.0f }, 1, false },
        { "stamina_deficit", "Vitals", { CurveKind::Logistic, 0.5f, 10.0f }, 1, false },
        { "health_falling", "Vitals", { CurveKind::Logistic, 0.03f, 150.0f }, 2, false },
        { "magicka_burn", "Vitals", { CurveKind::Logistic, 0.05f, 100.0f }, 3, false },
        { "stamina_burn", "Vitals", { CurveKind::Logistic, 0.05f, 100.0f }, 3, false },
        { "restore_pending_health", "Vitals", { CurveKind::Logistic, 0.8f, 12.0f }, 2, false },
        { "restore_pending_magicka", "Vitals", { CurveKind::Logistic, 0.8f, 12.0f }, 3, false },
        { "restore_pending_stamina", "Vitals", { CurveKind::Logistic, 0.8f, 12.0f }, 3, false },
        { "fire_damage_rate", "Elemental threat", { CurveKind::Logistic, 0.15f, 20.0f }, 1, false },
        { "frost_damage_rate", "Elemental threat", { CurveKind::Logistic, 0.15f, 20.0f }, 1, false },
        { "shock_damage_rate", "Elemental threat", { CurveKind::Logistic, 0.15f, 20.0f }, 1, false },
        { "magic_damage_rate", "Elemental threat", { CurveKind::Logistic, 0.15f, 20.0f }, 2, false },
        { "physical_damage_rate", "Elemental threat", { CurveKind::Logistic, 0.15f, 20.0f }, 2, false },
        { "enemy_casting_fire", "Elemental threat", { CurveKind::Linear, 2.0f, 0.0f }, 2, false },
        { "enemy_casting_frost", "Elemental threat", { CurveKind::Linear, 2.0f, 0.0f }, 2, false },
        { "enemy_casting_shock", "Elemental threat", { CurveKind::Linear, 2.0f, 0.0f }, 2, false },
        { "poisoned", "Status", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "diseased", "Status", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "drain_health", "Status", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "drain_magicka", "Status", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "drain_stamina", "Status", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "regen_suppressed", "Status", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "healing_blocked", "Status", { CurveKind::Step, 0.5f, 0.0f }, 2, true },
        { "encumbrance", "Status", { CurveKind::Logistic, 0.95f, 40.0f }, 1, false },
        { "vampire_sun_exposure", "Status", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "hunger", "Survival", { CurveKind::Quadratic, 0.0f, 1.0f }, 1, false },
        { "thirst", "Survival", { CurveKind::Quadratic, 0.0f, 1.0f }, 2, true },
        { "cold", "Survival", { CurveKind::Quadratic, 0.0f, 1.0f }, 1, false },
        { "fatigue", "Survival", { CurveKind::Quadratic, 0.0f, 1.0f }, 2, false },
        { "warmth_deficit", "Survival", { CurveKind::Linear, 0.0f, 1.0f }, 3, false },
        { "in_combat", "Enemy", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "combat_onset", "Enemy", { CurveKind::Gaussian, 0.0f, 10.0f }, 2, false },
        { "enemy_count", "Enemy", { CurveKind::Saturating, 5.0f, 0.0f }, 1, false },
        { "enemy_close", "Enemy", { CurveKind::Logistic, 300.0f, -0.02f }, 2, false },
        { "enemy_mid", "Enemy", { CurveKind::Gaussian, 600.0f, 200.0f }, 2, false },
        { "enemy_far", "Enemy", { CurveKind::Logistic, 1000.0f, 0.01f }, 2, false },
        { "surrounded", "Enemy", { CurveKind::Saturating, 5.0f, 0.0f }, 3, false },
        { "enemy_casting", "Enemy", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "target_caster", "Enemy", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_archer", "Enemy", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_health_low", "Enemy", { CurveKind::Logistic, 0.75f, 12.0f }, 3, false },
        { "boss_fight", "Enemy", { CurveKind::Logistic, 30.0f, 0.2f }, 2, false },
        { "target_magicka_low", "Enemy", { CurveKind::Logistic, 0.7f, 10.0f }, 3, true },
        { "target_stamina_low", "Enemy", { CurveKind::Logistic, 0.7f, 10.0f }, 3, true },
        { "target_humanoid", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 2, false },
        { "target_undead", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "target_daedra", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "target_dragon", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "target_construct", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_animal", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_arthropod", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 2, false },
        { "target_troll", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 2, false },
        { "target_giant", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_werebeast", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 2, false },
        { "target_monster", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_spectral", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_element_fire", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_element_frost", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_element_shock", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "target_summoned", "Target type", { CurveKind::Step, 0.5f, 0.0f }, 2, false },
        { "ally_injured", "Ally", { CurveKind::Logistic, 0.5f, 10.0f }, 1, false },
        { "follower_present", "Ally", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "darkness", "Environment", { CurveKind::Logistic, 0.65f, 15.0f }, 1, false },
        { "underwater", "Environment", { CurveKind::Logistic, 0.5f, 10.0f }, 1, false },
        { "swimming", "Environment", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "falling", "Environment", { CurveKind::Linear, 200.0f, 600.0f }, 1, false },
        { "drop_ahead", "Environment", { CurveKind::Logistic, 600.0f, 0.01f }, 3, false },
        { "lock_in_crosshair", "Environment", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "workstation_smithing", "Environment", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "workstation_enchanting", "Environment", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "workstation_alchemy", "Environment", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "ore_vein_in_crosshair", "Environment", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "merchant_in_crosshair", "Environment", { CurveKind::Step, 0.5f, 0.0f }, 2, false },
        { "weapon_charge_deficit", "Equipment", { CurveKind::Logistic, 0.75f, 12.0f }, 1, false },
        { "ammo_low", "Equipment", { CurveKind::Logistic, 0.6f, 10.0f }, 1, false },
        { "hands_empty", "Equipment", { CurveKind::Step, 0.5f, 0.0f }, 2, false },
        { "loadout_one_handed", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_two_handed", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_archery", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_staff", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_shield", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_destruction", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_conjuration", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_restoration", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_alteration", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "loadout_illusion", "Loadout", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "sneaking", "Activity", { CurveKind::Step, 0.5f, 0.0f }, 1, false },
        { "sneak_detected", "Activity", { CurveKind::Step, 0.5f, 0.0f }, 3, true },
        { "mounted", "Activity", { CurveKind::Step, 0.5f, 0.0f }, 3, false },
        { "downtime", "Activity", { CurveKind::Logistic, 20.0f, 0.3f }, 2, false },
        { "combat_ended_recent", "Activity", { CurveKind::Decay, 15.0f, 0.0f }, 3, false },
    } };

    [[nodiscard]] constexpr std::size_t Index(NeedId id) noexcept { return static_cast<std::size_t>(id); }
    [[nodiscard]] constexpr const NeedInfo& Info(NeedId id) noexcept { return kNeeds[Index(id)]; }
    [[nodiscard]] constexpr std::string_view Name(NeedId id) noexcept { return Info(id).id; }

    [[nodiscard]] constexpr std::optional<NeedId> FromName(std::string_view name) noexcept
    {
        for (std::size_t i = 0; i < kNeedCount; ++i) {
            if (kNeeds[i].id == name) return static_cast<NeedId>(i);
        }
        return std::nullopt;
    }
}
